### ISSUE TITLE
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])

### ISSUE THREAD

**Issue by RHodgett** [erzk/zooplaR#1]
Hi,

I get the following error when installing:

> devtools::install_github("erzk/zooplaR")
Downloading GitHub repo erzk/zooplaR@master
from URL https://api.github.com/repos/erzk/zooplaR/zipball/master
Installing zooplaR
"C:/PROGRA~1/R/R-32~1.0/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "XXXXXX/Local/Temp/RtmpMndZLz/devtools2f3059364d9f/erzk-zooplaR-b6744eb"  \
  --library="XXXXXXXX/R/win-library/3.2" --install-tests 

* installing *source* package 'zooplaR' ...
** R
** tests
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'XML' 3.98-1.3 is being loaded, but >= 3.98.1.5 is required
ERROR: lazy loading failed for package 'zooplaR'
* removing 'XXXXXXXXXX/R/win-library/3.2/zooplaR'
Error: Command failed (1)
> 

Seems a problem with XML, is there a fix for this?

Thanks,
Richard

**Comment by erykwalczak** [comment]
Hi Richard,
It seems like you are using an old version of the XML package. Updating your package should solve the issue. Please let me know if that solved the issue. The package is still in an early stage and it hasn't been tested properly.

**Comment by RHodgett** [comment]
Perfect, that worked. Many thanks. 

I'll try to test it in the coming weeks and feed back :)

**Comment by RHodgett** [comment]
Just out of interest do you have 1-2 examples of how the package could be used?

**Comment by erykwalczak** [comment]
Each completed function contains examples. You can check them in the package documentation or run `?` with a function name (e.g. `?average_sold_prices`)

**Comment by RHodgett** [comment]
Many thanks!
