### ISSUE TITLE
Property listing returns the same listing

### ISSUE THREAD

**Issue by bobokdalibor** [erzk/zooplaR#2]
When property listings in the area are queried, even if there are multiple results, it brings back the same property listing. Compared this to Zoopla API I/O where the results are correct.

**Comment by erykwalczak** [comment]
Can you share the code? Otherwise I can't reproduce the error.

**Comment by bobokdalibor** [comment]
Sorry, I just noticed where the issue lies.
If you explore the returned list from function `property_listing` through `View()` and go to individual listings, they will all have the same _listing_id_. This might be due to the fact that all returned listings are called _listing_ in the returned list.

This doesn't happen when you call functions on _property_id_ through console.
